# Generated by Django 4.0.2 on 2022-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide_id', models.CharField(max_length=7)),
                ('office', models.CharField(max_length=500)),
                ('quarter', models.IntegerField()),
                ('program', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('sort_sequence', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('transcode', models.CharField(max_length=15)),
                ('recordid', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
